use utoipa::OpenApi;
use crate::auth::claims::Claims;
use crate::auth::error::{AuthError,AuthErrorCode,AuthErrorDetailVariant,Error};
use crate::dto::admin_ai::{AIEngineDetail, AIEngineUpdate, AIEngineValidation, AiModel,AIEngineModels, AiModelCapabilities};
use crate::dto::admin_embedding::{EmbeddingConfigResponse, EmbeddingConfigUpdateRequest};
use crate::dto::admin_department_budget::{DepartmentBudgetStatus, SubDepartmentBudgetDto};
use crate::dto::admin_department::{DepartmentListQuery, DepartmentMembersResponse, DepartmentCreate, Department, DepartmentTreeNode, DepartmentTreeQuery, DepartmentTree, DepartmentsListResponse, DepartmentMove};
use crate::dto::me::MeDepartmentUsersResponse;
use crate::dto::notifications::{NotificationDto, NotificationsListQuery, NotificationsListResponse};
use crate::dto::mcp::{
    BulkToolAccessUpdate, BulkToolAccessUpdateResponse, McpAccessRule, McpAccessRuleInput,
    McpAuthorize, McpDisconnect, McpOauthCallback, McpServer,
    McpServerAccessList, McpServerAccessUpdate, McpServerCatalogEntry,
    McpServerCatalogResponse, McpServerCreate, McpServerTestResult, McpServerUpdate,
    McpSyncResult, McpTool, McpToolAccess, McpToolAccessUpdate, McpToolExecution,
    McpToolSummary, McpTools, McpUserConnection, McpUserConnections,
    PaginatedMcpServers, PaginatedMcpToolExecutions, McpEffectiveAccessResponse,
    McpEffectiveServerAccess, McpEffectiveToolAccess, McpResolvedVia,
};
use crate::dto::admin_mcp::{McpAccessDefault, McpServerAccess};
use crate::dto::admin_roles::{PermissionDto, PermissionsResponse, RoleDto, RoleRequest, RoleUpdateRequest, RolesResponse, UserRoleAssignmentDto, UserRoleAssignmentInput, UserRoleAssignmentsResponse};
use crate::dto::analytics::{
    AnalyticsOverview, AnalyticsTimeSeries, DepartmentAnalytics, DepartmentAnalyticsQuery,
    ScopedUserAnalyticsQuery, UserAnalytics,
};
use crate::dto::branding::{Branding, BrandingUpdate};
use crate::dto::admin_sso_providers::{SsoProvider, SsoProviderUpdate};
use crate::dto::admin_user::{User, UserPatchRequest, UserCreate, PaginatedUsers, UserUpdate};
use crate::dto::chat::{
    ArchiveChatRequest, ConversationResponse, MessageParts, MessageResponse, PaginatedConversations,
    TokenUsage,
};
use crate::dto::chat_stream::{ChatInput, ChatStream};
use crate::dto::common::{PaginationQuery, SortRule};
use crate::dto::files::{Attachment, File, FileResponse, FileUploadRequest};
use crate::dto::models::{ModelInfo, ProviderInfo};
use crate::dto::oauth::AuthCallback;
use crate::dto::me::EffectivePermissionsResponse;
use crate::error::{AppError, ErrorDetail, ErrorDetailVariant, ErrorResponse};
use crate::docs::{security::ApiSecurityAddon,app_error_catlog::AppErrorCatalogItem};
use crate::dto::auth::{AuthInit, AuthToken, RefreshToken, TokenType};
use crate::handlers::{auth,admin_department,admin_department_budgets,admin_analytics,admin_mcp,admin_roles,notifications,oidc,open_error,chat,chat_stream,file,message,admin_users,admin_sso_provider,branding,admin_ai,admin_embedding,models,me,mcp};
use crate::models::messages::ChatRole;
use crate::models::departments::{ActionOnExceed, BudgetPeriod};
use crate::models::mcp_access_policies::{McpAccessType, McpPermission};
use crate::models::mcp_servers::{McpDefaultAccess, McpTransportType};
use crate::models::users::UserStatus;

#[derive(OpenApi)]
#[openapi(
    paths(
        auth::handle_refresh_token,
        oidc::oidc_login_start,
        oidc::oidc_oauth_callback_get,
        oidc::oidc_oauth_callback_post,
        chat::get_chat_by_id,
        chat::get_chats,
        chat::delete_chat_by_id,
        chat::update_chat_by_id,
        chat_stream::handle_chat_stream_doc,
        chat_stream::handle_chat_stream_path_doc,
        message::delete_chat_message_by_id,
        message::edit_chat_message_by_id_and_stream,
        admin_users::add_new_user,
        admin_users::get_users,
        admin_users::update_user,
        admin_users::delete_user,
        admin_users::get_user_by_id,
        admin_users::patch_user_status,
        branding::get_branding,
        branding::get_admin_branding,
        branding::update_branding,
        admin_embedding::get_embedding_config,
        admin_embedding::update_embedding_config,
        admin_ai::get_ai_engines,
        admin_ai::update_ai_engines_by_key,
        admin_ai::get_ai_engines_by_key,
        admin_ai::validate_ai_engines_by_key,
        admin_ai::delete_ai_engines_api_key_key,
        admin_ai::get_ai_engine_models_by_key,
        admin_sso_provider::get_sso_providers,
        admin_sso_provider::get_sso_provider_by_id,
        admin_sso_provider::update_sso_provider_by_id,
        admin_sso_provider::delete_sso_provider_by_id,
        file::get_file_by_id,
        file::get_files,
        file::delete_file_by_id,
        file::download_file,
        file::upload_file,
        models::get_list_models,
        open_error::get_app_error_catalog,
        open_error::get_auth_error_catalog,
        admin_analytics::get_analytics_overview,
        admin_analytics::get_user_analytics,
        admin_analytics::get_timeseries_analytics,
        admin_analytics::get_department_analytics,
        admin_department::create_department,
        admin_department::update_department,
        admin_department::delete_department,
        admin_department::get_department_by_id,
        admin_department::list_departments,
        admin_department::get_departments_tree,
        admin_department::move_department,
        admin_department::add_users_in_department,
        admin_department::remove_users_from_department,
        admin_department::get_users_from_department,
        admin_roles::get_permissions,
        admin_roles::list_roles,
        admin_roles::create_role,
        admin_roles::get_role_by_id,
        admin_roles::update_role,
        admin_roles::delete_role,
        admin_roles::list_user_role_assignments,
        admin_roles::assign_role_to_user,
        admin_roles::remove_role_from_user,
        admin_mcp::get_mcp_server_access,
        admin_mcp::update_mcp_server_access,
        admin_mcp::update_mcp_server_default,
        admin_mcp::create_mcp_access_rule,
        admin_mcp::delete_mcp_access_rule,
        mcp::list_mcp_servers,
        mcp::list_public_mcp_servers,
        mcp::create_mcp_server,
        mcp::get_mcp_server,
        mcp::update_mcp_server,
        mcp::delete_mcp_server,
        mcp::test_mcp_server,
        mcp::sync_mcp_server_tools,
        mcp::list_mcp_server_executions,
        mcp::get_mcp_server_tools_access,
        mcp::update_mcp_server_tools_access,
        mcp::get_mcp_tool_access,
        mcp::update_mcp_tool_access,
        mcp::list_mcp_tools,
        mcp::list_mcp_connections,
        mcp::authorize_mcp_connection,
        mcp::disconnect_mcp_connection,
        mcp::mcp_oauth_callback,
        mcp::get_mcp_effective_access,
        me::get_my_permissions,
        notifications::list_my_notifications,
        notifications::mark_notification_read,
        notifications::stream_my_notifications,
        me::get_my_administered_department_analytics,
        me::get_my_administered_department_user_analytics,
        me::get_my_administered_department_members,
        me::get_my_administered_departments_list,
        me::get_my_administered_departments_tree,
        admin_department_budgets::get_department_budget,
    ),
    components(
        schemas(
            AuthInit,
            AuthToken,
            TokenType,
            UserStatus,
            ChatRole,
            Claims,
            ErrorResponse,
            ErrorDetail,
            ErrorDetailVariant,
            ArchiveChatRequest,
            MessageResponse,
            ConversationResponse,
            PaginatedConversations,
            File,
            MessageParts,
            TokenUsage,
            ChatStream,
            ChatInput,
            Attachment,
            AuthCallback,
            SortRule,
            PaginationQuery,
            PaginatedUsers,
            UserUpdate,
            UserCreate,
            Branding,
            BrandingUpdate,
            User,
            UserPatchRequest,
            AIEngineDetail,
            AIEngineUpdate,
            EmbeddingConfigResponse,
            EmbeddingConfigUpdateRequest,
            FileResponse,
            FileUploadRequest,
            ProviderInfo,
            ModelInfo,
            AIEngineValidation,
            AIEngineModels,
            AiModel,
            AiModelCapabilities,
            SsoProvider,
            SsoProviderUpdate,
            AuthError,
            AppError,
            AuthErrorCode,
            AuthErrorDetailVariant,
            Error,
            RefreshToken,
            AppErrorCatalogItem,
            DepartmentListQuery,
            Department,
            DepartmentsListResponse,
            DepartmentCreate,
            DepartmentMembersResponse,
            MeDepartmentUsersResponse,
            NotificationDto,
            NotificationsListResponse,
            NotificationsListQuery,
            AnalyticsOverview,
            DepartmentAnalytics,
            DepartmentAnalyticsQuery,
            AnalyticsTimeSeries,
            UserAnalytics,
            ScopedUserAnalyticsQuery,
            BudgetPeriod,
            ActionOnExceed,
            DepartmentTreeQuery,
            DepartmentTreeNode,
            DepartmentTree,
            DepartmentMove,
            SubDepartmentBudgetDto,
            DepartmentBudgetStatus,
            PermissionDto,
            PermissionsResponse,
            RoleDto,
            RoleRequest,
            RoleUpdateRequest,
            RolesResponse,
            UserRoleAssignmentDto,
            UserRoleAssignmentInput,
            UserRoleAssignmentsResponse,
            McpAccessDefault,
            McpServerAccess,
            McpServer,
            McpServerCreate,
            McpServerUpdate,
            PaginatedMcpServers,
            McpServerTestResult,
            McpSyncResult,
            McpTool,
            McpToolSummary,
            McpTools,
            McpToolExecution,
            PaginatedMcpToolExecutions,
            McpServerCatalogEntry,
            McpServerCatalogResponse,
            McpAccessRule,
            McpAccessRuleInput,
            McpServerAccessList,
            McpServerAccessUpdate,
            McpToolAccess,
            McpToolAccessUpdate,
            BulkToolAccessUpdate,
            BulkToolAccessUpdateResponse,
            McpUserConnection,
            McpUserConnections,
            McpAuthorize,
            McpDisconnect,
            McpOauthCallback,
            EffectivePermissionsResponse,
            McpEffectiveAccessResponse,
            McpEffectiveServerAccess,
            McpEffectiveToolAccess,
            McpResolvedVia,
            McpDefaultAccess,
            McpTransportType,
            McpAccessType,
            McpPermission
        )
    ),
    tags(
        (name = "auth", description = "Authentication & user endpoints"),
        (name = "branding", description = "Branding configuration endpoints"),
        (name = "admin", description = "Admin endpoints"),
        (name = "me", description = "Current user permissions"),
        (name = "mcp", description = "MCP tools & connections"),
        (name = "root", description = "Root / health"),
    ),
    modifiers(
        &ApiSecurityAddon
    )
)]
pub struct ApiDoc;
