// SPDX-FileCopyrightText: 2026 Perter Technology Solutions Private Limited
// SPDX-License-Identifier: Apache-2.0

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ProviderPlugins::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ProviderPlugins::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::ProviderKey)
                            .text()
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(ProviderPlugins::Version).text().not_null())
                    .col(
                        ColumnDef::new(ProviderPlugins::Manifest)
                            .json_binary()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ProviderPlugins::Digest).text().not_null())
                    .col(ColumnDef::new(ProviderPlugins::Source).text().not_null())
                    .col(ColumnDef::new(ProviderPlugins::Status).text().not_null())
                    .col(
                        ColumnDef::new(ProviderPlugins::ValidationError)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::Configuration)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'{}'::jsonb")),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::BaseUrlOverride)
                            .text()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::AllowInsecureHttp)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::AllowPrivateNetwork)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ProviderPlugins::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ProviderCredentials::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ProviderCredentials::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::PluginId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::SlotId)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::EncryptedValue)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::Status)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::ValidatedAt)
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ProviderCredentials::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_provider_credentials_plugin")
                            .from(ProviderCredentials::Table, ProviderCredentials::PluginId)
                            .to(ProviderPlugins::Table, ProviderPlugins::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("uq_provider_credentials_plugin_slot")
                    .table(ProviderCredentials::Table)
                    .col(ProviderCredentials::PluginId)
                    .col(ProviderCredentials::SlotId)
                    .unique()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(ProviderCredentials::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(ProviderPlugins::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum ProviderPlugins {
    Table,
    Id,
    ProviderKey,
    Version,
    Manifest,
    Digest,
    Source,
    Status,
    ValidationError,
    Configuration,
    BaseUrlOverride,
    AllowInsecureHttp,
    AllowPrivateNetwork,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum ProviderCredentials {
    Table,
    Id,
    PluginId,
    SlotId,
    EncryptedValue,
    Status,
    ValidatedAt,
    CreatedAt,
    UpdatedAt,
}
