use sea_orm_migration::{
    prelude::*,
    sea_orm::JsonValue,
    sea_query::{Alias, IntoColumnDef},
};

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        ensure_mcp_servers(manager).await?;
        ensure_mcp_access_policies(manager).await?;
        ensure_mcp_tools(manager).await?;
        ensure_mcp_server_tools(manager).await?;
        ensure_mcp_executions(manager).await?;
        ensure_mcp_connections(manager).await?;
        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Err(DbErr::Migration(
            "MCP schema normalization cannot be reversed safely.".to_string(),
        ))
    }
}

async fn ensure_mcp_servers(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if !manager.has_table("mcp_servers").await? {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("mcp_servers"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("name")).string().not_null())
                    .col(ColumnDef::new(Alias::new("description")).text().null())
                    .col(
                        ColumnDef::new(Alias::new("transportType"))
                            .string()
                            .not_null()
                            .default("stdio"),
                    )
                    .col(
                        ColumnDef::new(Alias::new("connectionConfig"))
                            .json_binary()
                            .not_null()
                            .default(JsonValue::Object(Default::default())),
                    )
                    .col(ColumnDef::new(Alias::new("clientId")).string().null())
                    .col(ColumnDef::new(Alias::new("clientSecret")).text().null())
                    .col(ColumnDef::new(Alias::new("url")).string().null())
                    .col(
                        ColumnDef::new(Alias::new("enabled"))
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(ColumnDef::new(Alias::new("status")).string().null())
                    .col(ColumnDef::new(Alias::new("statusMessage")).text().null())
                    .col(
                        ColumnDef::new(Alias::new("toolCount"))
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(Alias::new("accessDefault"))
                            .string()
                            .not_null()
                            .default("deny"),
                    )
                    .col(
                        ColumnDef::new(Alias::new("defaultAccess"))
                            .string()
                            .not_null()
                            .default("explicit_only"),
                    )
                    .col(
                        ColumnDef::new(Alias::new("lastConnectedAt"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("lastSyncedAt"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("createdAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updatedAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }

    ensure_column(
        manager,
        "mcp_servers",
        "description",
        ColumnDef::new(Alias::new("description")).text().null(),
    )
    .await?;
    ensure_column(
        manager,
        "mcp_servers",
        "enabled",
        ColumnDef::new(Alias::new("enabled"))
            .boolean()
            .not_null()
            .default(true),
    )
    .await?;
    ensure_column(
        manager,
        "mcp_servers",
        "status",
        ColumnDef::new(Alias::new("status")).string().null(),
    )
    .await?;

    ensure_column_renamed(
        manager,
        "mcp_servers",
        "transport_type",
        "transportType",
        ColumnDef::new(Alias::new("transportType"))
            .string()
            .not_null()
            .default("stdio"),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "connection_config",
        "connectionConfig",
        ColumnDef::new(Alias::new("connectionConfig"))
            .json_binary()
            .not_null()
            .default(JsonValue::Object(Default::default())),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "client_id",
        "clientId",
        ColumnDef::new(Alias::new("clientId")).string().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "client_secret",
        "clientSecret",
        ColumnDef::new(Alias::new("clientSecret")).text().null(),
    )
    .await?;

    ensure_url_column(manager).await?;

    ensure_column_renamed(
        manager,
        "mcp_servers",
        "status_message",
        "statusMessage",
        ColumnDef::new(Alias::new("statusMessage")).text().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "tool_count",
        "toolCount",
        ColumnDef::new(Alias::new("toolCount"))
            .integer()
            .not_null()
            .default(0),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "access_default",
        "accessDefault",
        ColumnDef::new(Alias::new("accessDefault"))
            .string()
            .not_null()
            .default("deny"),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "default_access",
        "defaultAccess",
        ColumnDef::new(Alias::new("defaultAccess"))
            .string()
            .not_null()
            .default("explicit_only"),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "last_connected_at",
        "lastConnectedAt",
        ColumnDef::new(Alias::new("lastConnectedAt"))
            .timestamp_with_time_zone()
            .null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "last_synced_at",
        "lastSyncedAt",
        ColumnDef::new(Alias::new("lastSyncedAt"))
            .timestamp_with_time_zone()
            .null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "created_at",
        "createdAt",
        ColumnDef::new(Alias::new("createdAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_servers",
        "updated_at",
        "updatedAt",
        ColumnDef::new(Alias::new("updatedAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;

    Ok(())
}

async fn ensure_mcp_access_policies(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if !manager.has_table("mcp_access_policies").await? {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("mcp_access_policies"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("targetType")).string().not_null())
                    .col(ColumnDef::new(Alias::new("serverId")).uuid().null())
                    .col(ColumnDef::new(Alias::new("toolId")).uuid().null())
                    .col(ColumnDef::new(Alias::new("accessType")).string().not_null())
                    .col(ColumnDef::new(Alias::new("permission")).string().not_null())
                    .col(ColumnDef::new(Alias::new("roleName")).string().null())
                    .col(ColumnDef::new(Alias::new("departmentId")).uuid().null())
                    .col(ColumnDef::new(Alias::new("userId")).uuid().null())
                    .col(
                        ColumnDef::new(Alias::new("inheritFromServer"))
                            .boolean()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("createdAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(Alias::new("createdBy")).uuid().null())
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }

    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "target_type",
        "targetType",
        ColumnDef::new(Alias::new("targetType")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "server_id",
        "serverId",
        ColumnDef::new(Alias::new("serverId")).uuid().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "tool_id",
        "toolId",
        ColumnDef::new(Alias::new("toolId")).uuid().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "access_type",
        "accessType",
        ColumnDef::new(Alias::new("accessType")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "permission",
        "permission",
        ColumnDef::new(Alias::new("permission")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "role_name",
        "roleName",
        ColumnDef::new(Alias::new("roleName")).string().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "department_id",
        "departmentId",
        ColumnDef::new(Alias::new("departmentId")).uuid().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "user_id",
        "userId",
        ColumnDef::new(Alias::new("userId")).uuid().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "inherit_from_server",
        "inheritFromServer",
        ColumnDef::new(Alias::new("inheritFromServer"))
            .boolean()
            .null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "created_at",
        "createdAt",
        ColumnDef::new(Alias::new("createdAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_access_policies",
        "created_by",
        "createdBy",
        ColumnDef::new(Alias::new("createdBy")).uuid().null(),
    )
    .await?;

    Ok(())
}

async fn ensure_mcp_tools(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if !manager.has_table("mcp_tools").await? {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("mcp_tools"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("serverId")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("serverName")).string().not_null())
                    .col(ColumnDef::new(Alias::new("name")).string().not_null())
                    .col(
                        ColumnDef::new(Alias::new("originalName"))
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(Alias::new("description")).text().null())
                    .col(
                        ColumnDef::new(Alias::new("inputSchema"))
                            .json_binary()
                            .not_null()
                            .default(JsonValue::Object(Default::default())),
                    )
                    .col(
                        ColumnDef::new(Alias::new("parameters"))
                            .json_binary()
                            .not_null()
                            .default(JsonValue::Array(vec![])),
                    )
                    .col(
                        ColumnDef::new(Alias::new("enabled"))
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(Alias::new("isReadOnly"))
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Alias::new("inheritAccessFromServer"))
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(Alias::new("lastSyncedAt"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("createdAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updatedAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }

    ensure_column(
        manager,
        "mcp_tools",
        "description",
        ColumnDef::new(Alias::new("description")).text().null(),
    )
    .await?;
    ensure_column(
        manager,
        "mcp_tools",
        "enabled",
        ColumnDef::new(Alias::new("enabled"))
            .boolean()
            .not_null()
            .default(true),
    )
    .await?;

    ensure_column_renamed(
        manager,
        "mcp_tools",
        "server_id",
        "serverId",
        ColumnDef::new(Alias::new("serverId")).uuid().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "server_name",
        "serverName",
        ColumnDef::new(Alias::new("serverName")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "original_name",
        "originalName",
        ColumnDef::new(Alias::new("originalName"))
            .string()
            .not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "input_schema",
        "inputSchema",
        ColumnDef::new(Alias::new("inputSchema"))
            .json_binary()
            .not_null()
            .default(JsonValue::Object(Default::default())),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "parameters",
        "parameters",
        ColumnDef::new(Alias::new("parameters"))
            .json_binary()
            .not_null()
            .default(JsonValue::Array(vec![])),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "is_read_only",
        "isReadOnly",
        ColumnDef::new(Alias::new("isReadOnly"))
            .boolean()
            .not_null()
            .default(false),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "inherit_access_from_server",
        "inheritAccessFromServer",
        ColumnDef::new(Alias::new("inheritAccessFromServer"))
            .boolean()
            .not_null()
            .default(true),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "last_synced_at",
        "lastSyncedAt",
        ColumnDef::new(Alias::new("lastSyncedAt"))
            .timestamp_with_time_zone()
            .null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "created_at",
        "createdAt",
        ColumnDef::new(Alias::new("createdAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_tools",
        "updated_at",
        "updatedAt",
        ColumnDef::new(Alias::new("updatedAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;

    Ok(())
}

async fn ensure_mcp_server_tools(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if !manager.has_table("mcp_server_tools").await? {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("mcp_server_tools"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("serverId")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("toolId")).uuid().not_null())
                    .col(
                        ColumnDef::new(Alias::new("createdAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updatedAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }

    ensure_column_renamed(
        manager,
        "mcp_server_tools",
        "server_id",
        "serverId",
        ColumnDef::new(Alias::new("serverId")).uuid().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_server_tools",
        "tool_id",
        "toolId",
        ColumnDef::new(Alias::new("toolId")).uuid().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_server_tools",
        "created_at",
        "createdAt",
        ColumnDef::new(Alias::new("createdAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_server_tools",
        "updated_at",
        "updatedAt",
        ColumnDef::new(Alias::new("updatedAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;

    Ok(())
}

async fn ensure_mcp_executions(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if !manager.has_table("mcp_executions").await? {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("mcp_executions"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("serverId")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("serverName")).string().not_null())
                    .col(ColumnDef::new(Alias::new("toolName")).string().not_null())
                    .col(ColumnDef::new(Alias::new("conversationId")).uuid().null())
                    .col(ColumnDef::new(Alias::new("userId")).uuid().null())
                    .col(ColumnDef::new(Alias::new("userEmail")).string().null())
                    .col(ColumnDef::new(Alias::new("arguments")).json_binary().null())
                    .col(ColumnDef::new(Alias::new("result")).json_binary().null())
                    .col(
                        ColumnDef::new(Alias::new("isError"))
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Alias::new("durationMs")).integer().null())
                    .col(
                        ColumnDef::new(Alias::new("executedAt"))
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("createdAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }

    ensure_column_renamed(
        manager,
        "mcp_executions",
        "server_id",
        "serverId",
        ColumnDef::new(Alias::new("serverId")).uuid().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "server_name",
        "serverName",
        ColumnDef::new(Alias::new("serverName")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "tool_name",
        "toolName",
        ColumnDef::new(Alias::new("toolName")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "conversation_id",
        "conversationId",
        ColumnDef::new(Alias::new("conversationId")).uuid().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "user_id",
        "userId",
        ColumnDef::new(Alias::new("userId")).uuid().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "user_email",
        "userEmail",
        ColumnDef::new(Alias::new("userEmail")).string().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "is_error",
        "isError",
        ColumnDef::new(Alias::new("isError"))
            .boolean()
            .not_null()
            .default(false),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "duration_ms",
        "durationMs",
        ColumnDef::new(Alias::new("durationMs")).integer().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "executed_at",
        "executedAt",
        ColumnDef::new(Alias::new("executedAt"))
            .timestamp_with_time_zone()
            .not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_executions",
        "created_at",
        "createdAt",
        ColumnDef::new(Alias::new("createdAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;

    Ok(())
}

async fn ensure_mcp_connections(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if !manager.has_table("mcp_connections").await? {
        manager
            .create_table(
                Table::create()
                    .table(Alias::new("mcp_connections"))
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Alias::new("id"))
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Alias::new("userId")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("serverId")).uuid().not_null())
                    .col(ColumnDef::new(Alias::new("serverName")).string().not_null())
                    .col(
                        ColumnDef::new(Alias::new("connected"))
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Alias::new("connectedAt"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(Alias::new("expiresAt"))
                            .timestamp_with_time_zone()
                            .null(),
                    )
                    .col(ColumnDef::new(Alias::new("scopes")).json_binary().null())
                    .col(ColumnDef::new(Alias::new("accessToken")).text().null())
                    .col(ColumnDef::new(Alias::new("refreshToken")).text().null())
                    .col(ColumnDef::new(Alias::new("tokenType")).string().null())
                    .col(
                        ColumnDef::new(Alias::new("createdAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(Alias::new("updatedAt"))
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }

    ensure_column(
        manager,
        "mcp_connections",
        "connected",
        ColumnDef::new(Alias::new("connected"))
            .boolean()
            .not_null()
            .default(false),
    )
    .await?;

    ensure_column_renamed(
        manager,
        "mcp_connections",
        "user_id",
        "userId",
        ColumnDef::new(Alias::new("userId")).uuid().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "server_id",
        "serverId",
        ColumnDef::new(Alias::new("serverId")).uuid().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "server_name",
        "serverName",
        ColumnDef::new(Alias::new("serverName")).string().not_null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "connected_at",
        "connectedAt",
        ColumnDef::new(Alias::new("connectedAt"))
            .timestamp_with_time_zone()
            .null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "expires_at",
        "expiresAt",
        ColumnDef::new(Alias::new("expiresAt"))
            .timestamp_with_time_zone()
            .null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "access_token",
        "accessToken",
        ColumnDef::new(Alias::new("accessToken")).text().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "refresh_token",
        "refreshToken",
        ColumnDef::new(Alias::new("refreshToken")).text().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "token_type",
        "tokenType",
        ColumnDef::new(Alias::new("tokenType")).string().null(),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "created_at",
        "createdAt",
        ColumnDef::new(Alias::new("createdAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;
    ensure_column_renamed(
        manager,
        "mcp_connections",
        "updated_at",
        "updatedAt",
        ColumnDef::new(Alias::new("updatedAt"))
            .timestamp_with_time_zone()
            .not_null()
            .default(Expr::current_timestamp()),
    )
    .await?;

    Ok(())
}

async fn ensure_url_column(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    if manager.has_column("mcp_servers", "url").await? {
        return Ok(());
    }
    if manager.has_column("mcp_servers", "dbUrl").await? {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("mcp_servers"))
                    .rename_column(Alias::new("dbUrl"), Alias::new("url"))
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }
    if manager.has_column("mcp_servers", "db_url").await? {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("mcp_servers"))
                    .rename_column(Alias::new("db_url"), Alias::new("url"))
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }
    ensure_column(
        manager,
        "mcp_servers",
        "url",
        ColumnDef::new(Alias::new("url")).string().null(),
    )
    .await
}

async fn ensure_column<D>(
    manager: &SchemaManager<'_>,
    table: &str,
    column: &str,
    def: D,
) -> Result<(), DbErr>
where
    D: IntoColumnDef,
{
    let def = def.into_column_def();
    if !manager.has_column(table, column).await? {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new(table))
                    .add_column(def)
                    .to_owned(),
            )
            .await?;
    }
    Ok(())
}

async fn ensure_column_renamed<D>(
    manager: &SchemaManager<'_>,
    table: &str,
    from: &str,
    to: &str,
    def: D,
) -> Result<(), DbErr>
where
    D: IntoColumnDef,
{
    let def = def.into_column_def();
    if manager.has_column(table, to).await? {
        return Ok(());
    }
    if manager.has_column(table, from).await? {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new(table))
                    .rename_column(Alias::new(from), Alias::new(to))
                    .to_owned(),
            )
            .await?;
        return Ok(());
    }
    manager
        .alter_table(
            Table::alter()
                .table(Alias::new(table))
                .add_column(def)
                .to_owned(),
        )
        .await?;
    Ok(())
}
