// SPDX-FileCopyrightText: 2026 Perter Technology Solutions Private Limited
// SPDX-License-Identifier: Apache-2.0

pub mod admin_ai;
pub mod admin_ai_plugins;
pub mod admin_analytics;
pub mod admin_audit;
pub mod admin_department;
pub mod admin_department_budgets;
pub mod admin_embedding;
pub mod admin_mcp;
pub mod admin_prompts;
pub mod admin_reconfigure;
pub mod admin_roles;
pub mod admin_sso_provider;
pub mod admin_system;
pub mod admin_users;
pub mod artifacts;
pub mod auth;
pub mod branding;
pub mod chat;
pub mod chat_stream;
pub mod file;
pub mod mcp;
pub mod me;
pub mod me_prompts;
pub mod me_skills;
pub mod message;
pub mod models;
pub mod notifications;
pub mod oidc;
pub mod open_error;
pub mod projects;
pub mod skills;
